INSERT INTO Company (vatNumber, name, shortName) VALUES ('PT503933813', 'Infraestruturas de Portugal, SA', 'IP');
INSERT INTO Company (vatNumber, name, shortName) VALUES ('PT509017800', 'Medway - Operador Ferroviário de Mercadorias, S.A', 'Medway');
INSERT INTO Company (vatNumber, name, shortName) VALUES ('PT507832388', 'Captrain Portugal S.A.', 'Captrain');

INSERT INTO Owner (ManagingVatNumber) VALUES ('PT503933813');

INSERT INTO Operator (ManagingVatNumber) VALUES ('PT509017800');
INSERT INTO Operator (ManagingVatNumber) VALUES ('PT507832388');

INSERT INTO Manufacture (manufacturerID, name) VALUES (1, 'Siemens');
INSERT INTO Manufacture (manufacturerID, name) VALUES (2, 'Sorefame - Alsthom');
INSERT INTO Manufacture (manufacturerID, name) VALUES (3, 'Stadler');
INSERT INTO Manufacture (manufacturerID, name) VALUES (4, 'Metalsines');
INSERT INTO Manufacture (manufacturerID, name) VALUES (5, 'Equimetal');
INSERT INTO Manufacture (manufacturerID, name) VALUES (6, 'Sepsa Cometna');
INSERT INTO Manufacture (manufacturerID, name) VALUES (7, 'Emef');
INSERT INTO Manufacture (manufacturerID, name) VALUES (8, 'Simmering');

INSERT INTO Gauge (gaugeID, gaugeWidth) VALUES (1, 1668);
INSERT INTO Gauge (gaugeID, gaugeWidth) VALUES (2, 1435);

INSERT INTO RollingStockDimension (id, length, width, height, weight) VALUES (1, 19, 3, 4, 87);
INSERT INTO RollingStockDimension (id, length, width, height, weight) VALUES (2, 19, 3, 4, 117);
INSERT INTO RollingStockDimension (id, length, width, height, weight) VALUES (3, 17, 3, 4, 24);
INSERT INTO RollingStockDimension (id, length, width, height, weight) VALUES (4, 10, 3, 4, 14);
INSERT INTO RollingStockDimension (id, length, width, height, weight) VALUES (5, 22, 3, 4, 30);
INSERT INTO RollingStockDimension (id, length, width, height, weight) VALUES (6, 14, 3, 3, 21);
INSERT INTO RollingStockDimension (id, length, width, height, weight) VALUES (7, 14, 3, 1, 12);
INSERT INTO RollingStockDimension (id, length, width, height, weight) VALUES (8, 18, 3, 1, 22);
INSERT INTO RollingStockDimension (id, length, width, height, weight) VALUES (9, 23, 3, 4, 124);
INSERT INTO RollingStockDimension (id, length, width, height, weight) VALUES (10, 13, 3, 4, 23);
INSERT INTO RollingStockDimension (id, length, width, height, weight) VALUES (11, 14, 3, 3, 14);

INSERT INTO Facility (facilityId, name) VALUES (1, 'São Romão');
INSERT INTO Facility (facilityId, name) VALUES (2, 'Tamel');
INSERT INTO Facility (facilityId, name) VALUES (3, 'Senhora das Dores');
INSERT INTO Facility (facilityId, name) VALUES (4, 'Lousado');
INSERT INTO Facility (facilityId, name) VALUES (5, 'Porto Campanhã');
INSERT INTO Facility (facilityId, name) VALUES (6, 'Leandro');
INSERT INTO Facility (facilityId, name) VALUES (7, 'Porto São Bento');
INSERT INTO Facility (facilityId, name) VALUES (8, 'Barcelos');
INSERT INTO Facility (facilityId, name) VALUES (9, 'Vila Nova da Cerveira');
INSERT INTO Facility (facilityId, name) VALUES (10, 'Midões');
INSERT INTO Facility (facilityId, name) VALUES (11, 'Valença');
INSERT INTO Facility (facilityId, name) VALUES (12, 'Darque');
INSERT INTO Facility (facilityId, name) VALUES (13, 'Contumil');
INSERT INTO Facility (facilityId, name) VALUES (14, 'Ermesinde');
INSERT INTO Facility (facilityId, name) VALUES (15, 'São Frutuoso');
INSERT INTO Facility (facilityId, name) VALUES (16, 'São Pedro da Torre');
INSERT INTO Facility (facilityId, name) VALUES (17, 'Viana do Castelo');
INSERT INTO Facility (facilityId, name) VALUES (18, 'Famalicão');
INSERT INTO Facility (facilityId, name) VALUES (19, 'Barroselas');
INSERT INTO Facility (facilityId, name) VALUES (20, 'Nine');
INSERT INTO Facility (facilityId, name) VALUES (21, 'Caminha');
INSERT INTO Facility (facilityId, name) VALUES (22, 'Carvalha');
INSERT INTO Facility (facilityId, name) VALUES (23, 'Carreço');
INSERT INTO Facility (facilityId, name) VALUES (43, 'São Gemil');
INSERT INTO Facility (facilityId, name) VALUES (45, 'São Mamede de Infesta');
INSERT INTO Facility (facilityId, name) VALUES (48, 'Leça do Bailo');
INSERT INTO Facility (facilityId, name) VALUES (50, 'Leixões');

INSERT INTO Line (lineId, name, startFacilityId, endFacilityId, gaugeID, "start", "end", OwnerManagingVatNumber) VALUES (1, 'Ramal São Bento - Campanhã', 7, 5, 1, 'Porto São Bento', 'Porto Campanhã', 'PT503933813');
INSERT INTO Line (lineId, name, startFacilityId, endFacilityId, gaugeID, "start", "end", OwnerManagingVatNumber) VALUES (2, 'Ramal Campanhã - Contumil', 5, 13, 1, 'Porto Campanhã', 'Contumil', 'PT503933813');
INSERT INTO Line (lineId, name, startFacilityId, endFacilityId, gaugeID, "start", "end", OwnerManagingVatNumber) VALUES (3, 'Ramal Contumil - Nine', 13, 20, 1, 'Contumil', 'Nine', 'PT503933813');
INSERT INTO Line (lineId, name, startFacilityId, endFacilityId, gaugeID, "start", "end", OwnerManagingVatNumber) VALUES (4, 'Ramal Nine - Barcelos', 20, 8, 1, 'Nine', 'Barcelos', 'PT503933813');
INSERT INTO Line (lineId, name, startFacilityId, endFacilityId, gaugeID, "start", "end", OwnerManagingVatNumber) VALUES (5, 'Ramal Barcelos - Darque', 8, 12, 1, 'Barcelos', 'Darque', 'PT503933813');
INSERT INTO Line (lineId, name, startFacilityId, endFacilityId, gaugeID, "start", "end", OwnerManagingVatNumber) VALUES (6, 'Ramal Darque - Viana', 12, 17, 1, 'Darque', 'Viana do Castelo', 'PT503933813');
INSERT INTO Line (lineId, name, startFacilityId, endFacilityId, gaugeID, "start", "end", OwnerManagingVatNumber) VALUES (7, 'Ramal Viana - Caminha', 17, 21, 1, 'Viana do Castelo', 'Caminha', 'PT503933813');
INSERT INTO Line (lineId, name, startFacilityId, endFacilityId, gaugeID, "start", "end", OwnerManagingVatNumber) VALUES (8, 'Ramal Caminha - Torre', 21, 16, 1, 'Caminha', 'São Pedro da Torre', 'PT503933813');
INSERT INTO Line (lineId, name, startFacilityId, endFacilityId, gaugeID, "start", "end", OwnerManagingVatNumber) VALUES (9, 'Ramal Torre - Valença', 16, 11, 1, 'São Pedro da Torre', 'Valença', 'PT503933813');
INSERT INTO Line (lineId, name, startFacilityId, endFacilityId, gaugeID, "start", "end", OwnerManagingVatNumber) VALUES (21, 'Ramal Contumil - São Gemil', 13, 43, 1, 'Contumil', 'São Gemil', 'PT503933813');
INSERT INTO Line (lineId, name, startFacilityId, endFacilityId, gaugeID, "start", "end", OwnerManagingVatNumber) VALUES (22, 'Ramal São Gemil - São Mamede de Infesta', 43, 45, 1, 'São Gemil', 'São Mamede de Infesta', 'PT503933813');
INSERT INTO Line (lineId, name, startFacilityId, endFacilityId, gaugeID, "start", "end", OwnerManagingVatNumber) VALUES (23, 'Ramal São Mamede de Infesta - Leça do Balio', 45, 48, 1, 'São Mamede de Infesta', 'Leça do Bailo', 'PT503933813');
INSERT INTO Line (lineId, name, startFacilityId, endFacilityId, gaugeID, "start", "end", OwnerManagingVatNumber) VALUES (24, 'Ramal Leça do Balio - Leixões', 48, 50, 1, 'Leça do Bailo', 'Leixões', 'PT503933813');
INSERT INTO Line (lineId, name, startFacilityId, endFacilityId, gaugeID, "start", "end", OwnerManagingVatNumber) VALUES (30, 'Ramal Braga', 31, 30, 1, 'Manzagão', 'Braga', 'PT503933813');
INSERT INTO Line (lineId, name, startFacilityId, endFacilityId, gaugeID, "start", "end", OwnerManagingVatNumber) VALUES (31, 'Ramal Nine - Manzagão', 20, 31, 1, 'Nine', 'Manzagão', 'PT503933813');
INSERT INTO Line (lineId, name, startFacilityId, endFacilityId, gaugeID, "start", "end", OwnerManagingVatNumber) VALUES (32, 'Ramal Manzagão - Cerqueiral', 31, 32, 1, 'Manzagão', 'Cerqueiral', 'PT503933813');
INSERT INTO Line (lineId, name, startFacilityId, endFacilityId, gaugeID, "start", "end", OwnerManagingVatNumber) VALUES (35, 'Ramal Cerqueiral - Gemieira', 32, 33, 1, 'Cerqueiral', 'Gemieira', 'PT503933813');
INSERT INTO Line (lineId, name, startFacilityId, endFacilityId, gaugeID, "start", "end", OwnerManagingVatNumber) VALUES (36, 'Ramal Gemieira - Paredes de Coura', 33, 35, 1, 'Gemieira', 'Paredes de Coura', 'PT503933813');
INSERT INTO Line (lineId, name, startFacilityId, endFacilityId, gaugeID, "start", "end", OwnerManagingVatNumber) VALUES (37, 'Ramal Paredes de Coura - Valença', 35, 11, 1, 'Paredes de Coura', 'Valença', 'PT503933813');

INSERT INTO Siding (id, position, length) VALUES (1, 2000, 864);
INSERT INTO Siding (id, position, length) VALUES (2, 11000, 266);

INSERT INTO LineSegment (lineId, "order", isElectrified, maxWeight, length, numberOfTracks, SidingId) VALUES (1, 1, 'Y', 8000, 2618, 4, NULL);
INSERT INTO LineSegment (lineId, "order", isElectrified, maxWeight, length, numberOfTracks, SidingId) VALUES (2, 1, 'Y', 8000, 2443, 4, NULL);
INSERT INTO LineSegment (lineId, "order", isElectrified, maxWeight, length, numberOfTracks, SidingId) VALUES (3, 1, 'Y', 8000, 26560, 2, NULL);
INSERT INTO LineSegment (lineId, "order", isElectrified, maxWeight, length, numberOfTracks, SidingId) VALUES (3, 2, 'Y', 8000, 10000, 2, NULL);
INSERT INTO LineSegment (lineId, "order", isElectrified, maxWeight, length, numberOfTracks, SidingId) VALUES (4, 1, 'Y', 8000, 5286, 2, NULL);
INSERT INTO LineSegment (lineId, "order", isElectrified, maxWeight, length, numberOfTracks, SidingId) VALUES (4, 2, 'Y', 8000, 6000, 2, NULL);
INSERT INTO LineSegment (lineId, "order", isElectrified, maxWeight, length, numberOfTracks, SidingId) VALUES (5, 1, 'Y', 8000, 10387, 2, NULL);
INSERT INTO LineSegment (lineId, "order", isElectrified, maxWeight, length, numberOfTracks, SidingId) VALUES (5, 2, 'Y', 8000, 12000, 2, NULL);
INSERT INTO LineSegment (lineId, "order", isElectrified, maxWeight, length, numberOfTracks, SidingId) VALUES (5, 3, 'Y', 8000, 3100, 2, NULL);
INSERT INTO LineSegment (lineId, "order", isElectrified, maxWeight, length, numberOfTracks, SidingId) VALUES (6, 1, 'Y', 6400, 4890, 2, NULL);
INSERT INTO LineSegment (lineId, "order", isElectrified, maxWeight, length, numberOfTracks, SidingId) VALUES (7, 1, 'Y', 8000, 6000, 1, NULL);
INSERT INTO LineSegment (lineId, "order", isElectrified, maxWeight, length, numberOfTracks, SidingId) VALUES (7, 2, 'Y', 8000, 5000, 1, 1);
INSERT INTO LineSegment (lineId, "order", isElectrified, maxWeight, length, numberOfTracks, SidingId) VALUES (7, 3, 'Y', 8000, 12000, 1, NULL);
INSERT INTO LineSegment (lineId, "order", isElectrified, maxWeight, length, numberOfTracks, SidingId) VALUES (8, 1, 'Y', 8000, 20829, 1, 2);
INSERT INTO LineSegment (lineId, "order", isElectrified, maxWeight, length, numberOfTracks, SidingId) VALUES (9, 1, 'Y', 8000, 4264, 1, NULL);
INSERT INTO LineSegment (lineId, "order", isElectrified, maxWeight, length, numberOfTracks, SidingId) VALUES (21, 1, 'Y', 8000, 3883, 2, NULL);
INSERT INTO LineSegment (lineId, "order", isElectrified, maxWeight, length, numberOfTracks, SidingId) VALUES (22, 1, 'Y', 8400, 1174, 2, NULL);
INSERT INTO LineSegment (lineId, "order", isElectrified, maxWeight, length, numberOfTracks, SidingId) VALUES (22, 2, 'Y', 8000, 2534, 2, NULL);
INSERT INTO LineSegment (lineId, "order", isElectrified, maxWeight, length, numberOfTracks, SidingId) VALUES (23, 1, 'Y', 8000, 1566, 2, NULL);
INSERT INTO LineSegment (lineId, "order", isElectrified, maxWeight, length, numberOfTracks, SidingId) VALUES (23, 2, 'Y', 8000, 1453, 2, NULL);
INSERT INTO LineSegment (lineId, "order", isElectrified, maxWeight, length, numberOfTracks, SidingId) VALUES (24, 1, 'Y', 8100, 3597, 2, NULL);
INSERT INTO LineSegment (lineId, "order", isElectrified, maxWeight, length, numberOfTracks, SidingId) VALUES (24, 2, 'Y', 8000, 4334, 2, NULL);

INSERT INTO RollingStockModel (id, model, numBogies, maxSpeed, bogies, RollingStockDimensionId, manufacturerId, multipleGauges) VALUES (1, 'Eurosprinter', 2, 220, 'Bo-Bo', 1, 1, 'N');
INSERT INTO RollingStockModel (id, model, numBogies, maxSpeed, bogies, RollingStockDimensionId, manufacturerId, multipleGauges) VALUES (2, 'CP 1900', 2, 100, 'Co-Co', 2, 2, 'N');
INSERT INTO RollingStockModel (id, model, numBogies, maxSpeed, bogies, RollingStockDimensionId, manufacturerId, multipleGauges) VALUES (3, 'E4000', 3, 120, 'Co-Co', 9, 3, 'Y');
INSERT INTO RollingStockModel (id, model, numBogies, maxSpeed, bogies, RollingStockDimensionId, manufacturerId, multipleGauges) VALUES (4, 'Regmms 32 94 356 3', 2, 120, 'Duplo', 6, 4, 'N');
INSERT INTO RollingStockModel (id, model, numBogies, maxSpeed, bogies, RollingStockDimensionId, manufacturerId, multipleGauges) VALUES (5, 'Tadgs 32 94 082 3', 2, 120, 'Duplo', 3, 4, 'N');
INSERT INTO RollingStockModel (id, model, numBogies, maxSpeed, bogies, RollingStockDimensionId, manufacturerId, multipleGauges) VALUES (6, 'Tdgs 41 94 074 1', 2, 100, 'Duplo', 4, 5, 'N');
INSERT INTO RollingStockModel (id, model, numBogies, maxSpeed, bogies, RollingStockDimensionId, manufacturerId, multipleGauges) VALUES (7, 'Gabs 81 94 181 1', 2, 100, 'Duplo', 5, 6, 'N');
INSERT INTO RollingStockModel (id, model, numBogies, maxSpeed, bogies, RollingStockDimensionId, manufacturerId, multipleGauges) VALUES (8, 'Lgs 22 94 441 6', 2, 120, 'Simples', 7, 4, 'N');
INSERT INTO RollingStockModel (id, model, numBogies, maxSpeed, bogies, RollingStockDimensionId, manufacturerId, multipleGauges) VALUES (9, 'Sgnss 12 94 455 2', 2, 120, 'Duplo', 8, 7, 'Y');
INSERT INTO RollingStockModel (id, model, numBogies, maxSpeed, bogies, RollingStockDimensionId, manufacturerId, multipleGauges) VALUES (10, 'Zaes 81 94 788', 2, 120, 'Duplo', 10, 5, 'Y');
INSERT INTO RollingStockModel (id, model, numBogies, maxSpeed, bogies, RollingStockDimensionId, manufacturerId, multipleGauges) VALUES (11, 'Kbs 41 94 333', 2, 100, 'Simples', 11, 8, 'N');

INSERT INTO RollingStock (id, startDate, RollingStockModelId, OperatorManagingVatNumber) VALUES (1, DATE '1995-01-01', 1, 'PT509017800');
INSERT INTO RollingStock (id, startDate, RollingStockModelId, OperatorManagingVatNumber) VALUES (2, DATE '1995-04-01', 1, 'PT509017800');
INSERT INTO RollingStock (id, startDate, RollingStockModelId, OperatorManagingVatNumber) VALUES (3, DATE '1996-01-02', 1, 'PT509017800');
INSERT INTO RollingStock (id, startDate, RollingStockModelId, OperatorManagingVatNumber) VALUES (4, DATE '1981-04-07', 2, 'PT509017800');
INSERT INTO RollingStock (id, startDate, RollingStockModelId, OperatorManagingVatNumber) VALUES (5, DATE '2017-02-15', 3, 'PT509017800');
INSERT INTO RollingStock (id, startDate, RollingStockModelId, OperatorManagingVatNumber) VALUES (6, DATE '2017-02-01', 3, 'PT509017800');
INSERT INTO RollingStock (id, startDate, RollingStockModelId, OperatorManagingVatNumber) VALUES (7, DATE '2019-05-07', 3, 'PT507832388');
INSERT INTO RollingStock (id, startDate, RollingStockModelId, OperatorManagingVatNumber) VALUES (8, DATE '2019-06-03', 3, 'PT507832388');
INSERT INTO RollingStock (id, startDate, RollingStockModelId, OperatorManagingVatNumber) VALUES (9, DATE '1987-05-02', 4, 'PT509017800');
INSERT INTO RollingStock (id, startDate, RollingStockModelId, OperatorManagingVatNumber) VALUES (10, DATE '1990-04-12', 5, 'PT509017800');
INSERT INTO RollingStock (id, startDate, RollingStockModelId, OperatorManagingVatNumber) VALUES (11, DATE '1977-02-03', 6, 'PT509017800');
INSERT INTO RollingStock (id, startDate, RollingStockModelId, OperatorManagingVatNumber) VALUES (12, DATE '1977-02-03', 7, 'PT509017800');
INSERT INTO RollingStock (id, startDate, RollingStockModelId, OperatorManagingVatNumber) VALUES (13, DATE '2005-09-01', 11, 'PT509017800');

INSERT INTO LocomotiveModel (locomotiveModelID, power, operationalSpeed, traction, RollingStockModelId) VALUES (1, 5600, 70, 300, 1);
INSERT INTO LocomotiveModel (locomotiveModelID, power, operationalSpeed, traction, RollingStockModelId) VALUES (2, 1623, 42.5, 396, 2);
INSERT INTO LocomotiveModel (locomotiveModelID, power, operationalSpeed, traction, RollingStockModelId) VALUES (3, 3178, 100, 400, 3);

INSERT INTO Locomotive (id, locomotiveModelID, name, RollingStockId) VALUES (5621, 1, 'Inês', 1);
INSERT INTO Locomotive (id, locomotiveModelID, name, RollingStockId) VALUES (5623, 1, 'Paz', 2);
INSERT INTO Locomotive (id, locomotiveModelID, name, RollingStockId) VALUES (5630, 1, 'Helena', 3);
INSERT INTO Locomotive (id, locomotiveModelID, name, RollingStockId) VALUES (1903, 2, 'Eva', 4);
INSERT INTO Locomotive (id, locomotiveModelID, name, RollingStockId) VALUES (5034, 3, 'Adriana', 5);
INSERT INTO Locomotive (id, locomotiveModelID, name, RollingStockId) VALUES (5036, 3, 'Marina', 6);
INSERT INTO Locomotive (id, locomotiveModelID, name, RollingStockId) VALUES (335001, 3, 'No Name', 7);
INSERT INTO Locomotive (id, locomotiveModelID, name, RollingStockId) VALUES (335003, 3, 'No Name', 8);

INSERT INTO ElectricLocomotiveType (locomotiveModelID, frequency, voltage) VALUES (1, 50, 25000);
INSERT INTO DieselLocomotiveType (locomotiveModelID, fuelCapacity) VALUES (2, 4882);
INSERT INTO DieselLocomotiveType (locomotiveModelID, fuelCapacity) VALUES (3, 6700);

INSERT INTO WagonType (typeId, name) VALUES (1, 'Cereal wagon');
INSERT INTO WagonType (typeId, name) VALUES (2, 'Covered wagon with sliding door');
INSERT INTO WagonType (typeId, name) VALUES (3, 'Container wagon (max 40'''' HC)');
INSERT INTO WagonType (typeId, name) VALUES (4, 'Biodiesel wagaon');
INSERT INTO WagonType (typeId, name) VALUES (5, 'Wood wagon');

INSERT INTO WagonModel (id, payLoad, volume, RollingStockModelId, WagonTypeId) VALUES (1245, 56, 75, 5, 1);
INSERT INTO WagonModel (id, payLoad, volume, RollingStockModelId, WagonTypeId) VALUES (1278, 26.2, 38, 4, 1);
INSERT INTO WagonModel (id, payLoad, volume, RollingStockModelId, WagonTypeId) VALUES (1325, 50.2, 110, 5, 2);
INSERT INTO WagonModel (id, payLoad, volume, RollingStockModelId, WagonTypeId) VALUES (1104, 60.6, 76.3, 6, 3);
INSERT INTO WagonModel (id, payLoad, volume, RollingStockModelId, WagonTypeId) VALUES (985, 28.1, 76.3, 7, 3);
INSERT INTO WagonModel (id, payLoad, volume, RollingStockModelId, WagonTypeId) VALUES (987, 68.4, 76.3, 8, 3);
INSERT INTO WagonModel (id, payLoad, volume, RollingStockModelId, WagonTypeId) VALUES (988, 68.4, 76.3, 8, 3);
INSERT INTO WagonModel (id, payLoad, volume, RollingStockModelId, WagonTypeId) VALUES (1525, 57.1, 64.6, 10, 4);
INSERT INTO WagonModel (id, payLoad, volume, RollingStockModelId, WagonTypeId) VALUES (1212, 25.8, 62.7, 11, 5);

INSERT INTO Wagon (wagonId, RollingStockId) VALUES ('356 3 077', 9);
INSERT INTO Wagon (wagonId, RollingStockId) VALUES ('356 3 078', 9);
INSERT INTO Wagon (wagonId, RollingStockId) VALUES ('356 3 079', 9);
INSERT INTO Wagon (wagonId, RollingStockId) VALUES ('356 3 080', 9);
INSERT INTO Wagon (wagonId, RollingStockId) VALUES ('356 3 081', 9);
INSERT INTO Wagon (wagonId, RollingStockId) VALUES ('356 3 082', 9);
INSERT INTO Wagon (wagonId, RollingStockId) VALUES ('356 3 083', 9);
INSERT INTO Wagon (wagonId, RollingStockId) VALUES ('356 3 084', 9);
INSERT INTO Wagon (wagonId, RollingStockId) VALUES ('356 3 085', 9);
INSERT INTO Wagon (wagonId, RollingStockId) VALUES ('356 3 086', 9);
INSERT INTO Wagon (wagonId, RollingStockId) VALUES ('356 3 087', 9);
INSERT INTO Wagon (wagonId, RollingStockId) VALUES ('356 3 088', 9);
INSERT INTO Wagon (wagonId, RollingStockId) VALUES ('356 3 089', 9);
INSERT INTO Wagon (wagonId, RollingStockId) VALUES ('356 3 090', 9);
INSERT INTO Wagon (wagonId, RollingStockId) VALUES ('356 3 091', 9);
INSERT INTO Wagon (wagonId, RollingStockId) VALUES ('356 3 092', 9);
INSERT INTO Wagon (wagonId, RollingStockId) VALUES ('082 3 045', 10);
INSERT INTO Wagon (wagonId, RollingStockId) VALUES ('082 3 046', 10);
INSERT INTO Wagon (wagonId, RollingStockId) VALUES ('082 3 047', 10);
INSERT INTO Wagon (wagonId, RollingStockId) VALUES ('082 3 048', 10);
INSERT INTO Wagon (wagonId, RollingStockId) VALUES ('074 1 001', 11);
INSERT INTO Wagon (wagonId, RollingStockId) VALUES ('074 1 002', 11);
INSERT INTO Wagon (wagonId, RollingStockId) VALUES ('074 1 003', 11);
INSERT INTO Wagon (wagonId, RollingStockId) VALUES ('074 1 004', 11);
INSERT INTO Wagon (wagonId, RollingStockId) VALUES ('074 1 005', 11);
INSERT INTO Wagon (wagonId, RollingStockId) VALUES ('074 1 006', 11);
INSERT INTO Wagon (wagonId, RollingStockId) VALUES ('181 1 010', 12);
INSERT INTO Wagon (wagonId, RollingStockId) VALUES ('181 1 011', 12);
INSERT INTO Wagon (wagonId, RollingStockId) VALUES ('181 1 012', 12);
INSERT INTO Wagon (wagonId, RollingStockId) VALUES ('181 1 013', 12);
INSERT INTO Wagon (wagonId, RollingStockId) VALUES ('181 1 014', 12);
INSERT INTO Wagon (wagonId, RollingStockId) VALUES ('333 0 001', 13);
INSERT INTO Wagon (wagonId, RollingStockId) VALUES ('333 0 002', 13);
INSERT INTO Wagon (wagonId, RollingStockId) VALUES ('333 0 003', 13);
INSERT INTO Wagon (wagonId, RollingStockId) VALUES ('333 0 004', 13);
INSERT INTO Wagon (wagonId, RollingStockId) VALUES ('333 0 005', 13);
INSERT INTO Wagon (wagonId, RollingStockId) VALUES ('333 0 006', 13);
INSERT INTO Wagon (wagonId, RollingStockId) VALUES ('333 0 007', 13);
INSERT INTO Wagon (wagonId, RollingStockId) VALUES ('333 0 008', 13);
INSERT INTO Wagon (wagonId, RollingStockId) VALUES ('333 0 009', 13);
INSERT INTO Wagon (wagonId, RollingStockId) VALUES ('333 0 010', 13);

INSERT INTO Train (id, maxLength, OperatorManagingVatNumber) VALUES (5421, 1000, 'PT509017800');
INSERT INTO Train (id, maxLength, OperatorManagingVatNumber) VALUES (5435, 1000, 'PT509017800');
INSERT INTO Train (id, maxLength, OperatorManagingVatNumber) VALUES (5437, 1000, 'PT509017800');
INSERT INTO Train (id, maxLength, OperatorManagingVatNumber) VALUES (5438, 1000, 'PT509017800');

INSERT INTO Freight (id, TrainId, origin, destination) VALUES (2001, 5421, 50, 12);
INSERT INTO Freight (id, TrainId, origin, destination) VALUES (2002, 5421, 13, 11);
INSERT INTO Freight (id, TrainId, origin, destination) VALUES (2003, 5421, 50, 11);
INSERT INTO Freight (id, TrainId, origin, destination) VALUES (2004, 5421, 50, 21);
INSERT INTO Freight (id, TrainId, origin, destination) VALUES (2005, 5421, 20, 11);
INSERT INTO Freight (id, TrainId, origin, destination) VALUES (2006, 5435, 12, 50);
INSERT INTO Freight (id, TrainId, origin, destination) VALUES (2050, 5437, 12, 50);
INSERT INTO Freight (id, TrainId, origin, destination) VALUES (2051, 5437, 11, 50);
INSERT INTO Freight (id, TrainId, origin, destination) VALUES (2007, 5438, 50, 5);

INSERT INTO Freight_Wagon (FreightId, WagonId) VALUES (2001, '333 0 001');
INSERT INTO Freight_Wagon (FreightId, WagonId) VALUES (2001, '333 0 002');
INSERT INTO Freight_Wagon (FreightId, WagonId) VALUES (2001, '333 0 004');
INSERT INTO Freight_Wagon (FreightId, WagonId) VALUES (2001, '333 0 005');
INSERT INTO Freight_Wagon (FreightId, WagonId) VALUES (2001, '333 0 006');
INSERT INTO Freight_Wagon (FreightId, WagonId) VALUES (2002, '356 3 089');
INSERT INTO Freight_Wagon (FreightId, WagonId) VALUES (2003, '181 1 011');
INSERT INTO Freight_Wagon (FreightId, WagonId) VALUES (2003, '181 1 012');
INSERT INTO Freight_Wagon (FreightId, WagonId) VALUES (2004, '181 1 013');
INSERT INTO Freight_Wagon (FreightId, WagonId) VALUES (2005, '356 3 077');
INSERT INTO Freight_Wagon (FreightId, WagonId) VALUES (2005, '356 3 078');
INSERT INTO Freight_Wagon (FreightId, WagonId) VALUES (2005, '356 3 079');
INSERT INTO Freight_Wagon (FreightId, WagonId) VALUES (2005, '356 3 080');
INSERT INTO Freight_Wagon (FreightId, WagonId) VALUES (2006, '333 0 003');
INSERT INTO Freight_Wagon (FreightId, WagonId) VALUES (2006, '333 0 007');
INSERT INTO Freight_Wagon (FreightId, WagonId) VALUES (2007, '356 3 090');
INSERT INTO Freight_Wagon (FreightId, WagonId) VALUES (2007, '356 3 091');
INSERT INTO Freight_Wagon (FreightId, WagonId) VALUES (2007, '356 3 092');
INSERT INTO Freight_Wagon (FreightId, WagonId) VALUES (2050, '333 0 001');
INSERT INTO Freight_Wagon (FreightId, WagonId) VALUES (2050, '333 0 002');
INSERT INTO Freight_Wagon (FreightId, WagonId) VALUES (2050, '333 0 004');
INSERT INTO Freight_Wagon (FreightId, WagonId) VALUES (2050, '333 0 005');
INSERT INTO Freight_Wagon (FreightId, WagonId) VALUES (2050, '333 0 006');
INSERT INTO Freight_Wagon (FreightId, WagonId) VALUES (2051, '181 1 011');
INSERT INTO Freight_Wagon (FreightId, WagonId) VALUES (2051, '181 1 012');
INSERT INTO Freight_Wagon (FreightId, WagonId) VALUES (2051, '356 3 077');
INSERT INTO Freight_Wagon (FreightId, WagonId) VALUES (2051, '356 3 078');
INSERT INTO Freight_Wagon (FreightId, WagonId) VALUES (2051, '356 3 079');
INSERT INTO Freight_Wagon (FreightId, WagonId) VALUES (2051, '356 3 080');

INSERT INTO Train_Locomotive (TrainId, LocomotiveId) VALUES (5421, 5621);
INSERT INTO Train_Locomotive (TrainId, LocomotiveId) VALUES (5438, 5623);
INSERT INTO Train_Locomotive (TrainId, LocomotiveId) VALUES (5435, 5623);
INSERT INTO Train_Locomotive (TrainId, LocomotiveId) VALUES (5437, 5621);

INSERT INTO Path ("order", trainId, pathId, departureTime, facilityId) VALUES ('50, 48, 45, 43, 13, 20, 8, 12, 17, 21, 16, 11', 5421, 1, TO_TIMESTAMP('2025-10-03 09:45:00', 'YYYY-MM-DD HH24:MI:SS'), 50);
INSERT INTO Path ("order", trainId, pathId, departureTime, facilityId) VALUES ('11, 16, 21, 17, 12, 8, 20, 13, 43, 45, 48, 50', 5435, 2, TO_TIMESTAMP('2025-10-03 18:00:00', 'YYYY-MM-DD HH24:MI:SS'), 11);
INSERT INTO Path ("order", trainId, pathId, departureTime, facilityId) VALUES ('11, 16, 21, 17, 12, 8, 20, 13, 43, 45, 48, 50', 5437, 3, TO_TIMESTAMP('2025-10-06 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), 11);

INSERT INTO Good (id, name) VALUES (1, 'Coal');
INSERT INTO Good (id, name) VALUES (2, 'Iron');
INSERT INTO Good (id, name) VALUES (3, 'Wood');
INSERT INTO Good (id, name) VALUES (4, 'Biodiesel');
INSERT INTO Good (id, name) VALUES (5, 'Steel');
INSERT INTO Good (id, name) VALUES (6, 'Cereal');

INSERT INTO Station (facilityID) VALUES (1);
INSERT INTO Station (facilityID) VALUES (2);
INSERT INTO Station (facilityID) VALUES (3);
INSERT INTO Station (facilityID) VALUES (4);
INSERT INTO Station (facilityID) VALUES (5);
INSERT INTO Station (facilityID) VALUES (7);
INSERT INTO Station (facilityID) VALUES (8);
INSERT INTO Station (facilityID) VALUES (11);
INSERT INTO Station (facilityID) VALUES (13);
INSERT INTO Station (facilityID) VALUES (14);
INSERT INTO Station (facilityID) VALUES (17);
INSERT INTO Station (facilityID) VALUES (20);
INSERT INTO Station (facilityID) VALUES (23);
INSERT INTO Station (facilityID) VALUES (45);

INSERT INTO Terminal (facilityID, intermodal) VALUES (6, 'Y');
INSERT INTO Terminal (facilityID, intermodal) VALUES (9, 'Y');
INSERT INTO Terminal (facilityID, intermodal) VALUES (10, 'N');
INSERT INTO Terminal (facilityID, intermodal) VALUES (12, 'Y');
INSERT INTO Terminal (facilityID, intermodal) VALUES (15, 'N');
INSERT INTO Terminal (facilityID, intermodal) VALUES (16, 'Y');
INSERT INTO Terminal (facilityID, intermodal) VALUES (18, 'N');
INSERT INTO Terminal (facilityID, intermodal) VALUES (19, 'Y');
INSERT INTO Terminal (facilityID, intermodal) VALUES (21, 'N');
INSERT INTO Terminal (facilityID, intermodal) VALUES (22, 'N');
INSERT INTO Terminal (facilityID, intermodal) VALUES (43, 'Y');
INSERT INTO Terminal (facilityID, intermodal) VALUES (48, 'N');
INSERT INTO Terminal (facilityID, intermodal) VALUES (50, 'Y');

INSERT INTO Building (id, name) VALUES (1, 'Passenger Terminal');
INSERT INTO Building (id, name) VALUES (2, 'Warehouse');
INSERT INTO Building (id, name) VALUES (3, 'Control Tower');
INSERT INTO Building (id, name) VALUES (4, 'Maintenance Workshop');

INSERT INTO Facility_Building (facilityID, buildingID) VALUES (5, 1);
INSERT INTO Facility_Building (facilityID, buildingID) VALUES (5, 3);
INSERT INTO Facility_Building (facilityID, buildingID) VALUES (50, 2);
INSERT INTO Facility_Building (facilityID, buildingID) VALUES (13, 4);


INSERT INTO RollingStockModel_Gauge (gaugeID, modelID) VALUES (1, 1);
INSERT INTO RollingStockModel_Gauge (gaugeID, modelID) VALUES (1, 2);
INSERT INTO RollingStockModel_Gauge (gaugeID, modelID) VALUES (1, 4);
INSERT INTO RollingStockModel_Gauge (gaugeID, modelID) VALUES (1, 5);
INSERT INTO RollingStockModel_Gauge (gaugeID, modelID) VALUES (1, 6);
INSERT INTO RollingStockModel_Gauge (gaugeID, modelID) VALUES (1, 7);
INSERT INTO RollingStockModel_Gauge (gaugeID, modelID) VALUES (1, 8);
INSERT INTO RollingStockModel_Gauge (gaugeID, modelID) VALUES (1, 11);
INSERT INTO RollingStockModel_Gauge (gaugeID, modelID) VALUES (1, 3);
INSERT INTO RollingStockModel_Gauge (gaugeID, modelID) VALUES (2, 3);
INSERT INTO RollingStockModel_Gauge (gaugeID, modelID) VALUES (1, 9);
INSERT INTO RollingStockModel_Gauge (gaugeID, modelID) VALUES (2, 9);
INSERT INTO RollingStockModel_Gauge (gaugeID, modelID) VALUES (1, 10);
INSERT INTO RollingStockModel_Gauge (gaugeID, modelID) VALUES (2, 10);

INSERT INTO Good_WagonType (GoodId, WagonTypeId) VALUES (6, 1);
INSERT INTO Good_WagonType (GoodId, WagonTypeId) VALUES (1, 3);
INSERT INTO Good_WagonType (GoodId, WagonTypeId) VALUES (2, 3);
INSERT INTO Good_WagonType (GoodId, WagonTypeId) VALUES (3, 5);
INSERT INTO Good_WagonType (GoodId, WagonTypeId) VALUES (4, 2);
INSERT INTO Good_WagonType (GoodId, WagonTypeId) VALUES (5, 2);
INSERT INTO Good_WagonType (GoodId, WagonTypeId) VALUES (4, 4);

INSERT INTO Wagon_Good (WagonId, GoodId) VALUES ('356 3 077', 1);
INSERT INTO Wagon_Good (WagonId, GoodId) VALUES ('356 3 078', 1);
INSERT INTO Wagon_Good (WagonId, GoodId) VALUES ('356 3 079', 1);
INSERT INTO Wagon_Good (WagonId, GoodId) VALUES ('356 3 080', 1);
INSERT INTO Wagon_Good (WagonId, GoodId) VALUES ('356 3 081', 1);
INSERT INTO Wagon_Good (WagonId, GoodId) VALUES ('356 3 082', 1);
INSERT INTO Wagon_Good (WagonId, GoodId) VALUES ('356 3 083', 1);
INSERT INTO Wagon_Good (WagonId, GoodId) VALUES ('356 3 084', 1);
INSERT INTO Wagon_Good (WagonId, GoodId) VALUES ('356 3 085', 1);
INSERT INTO Wagon_Good (WagonId, GoodId) VALUES ('356 3 086', 1);
INSERT INTO Wagon_Good (WagonId, GoodId) VALUES ('356 3 087', 1);
INSERT INTO Wagon_Good (WagonId, GoodId) VALUES ('356 3 088', 1);
INSERT INTO Wagon_Good (WagonId, GoodId) VALUES ('356 3 089', 2);
INSERT INTO Wagon_Good (WagonId, GoodId) VALUES ('356 3 090', 2);
INSERT INTO Wagon_Good (WagonId, GoodId) VALUES ('356 3 091', 2);
INSERT INTO Wagon_Good (WagonId, GoodId) VALUES ('356 3 092', 2);
INSERT INTO Wagon_Good (WagonId, GoodId) VALUES ('082 3 045', 6);
INSERT INTO Wagon_Good (WagonId, GoodId) VALUES ('082 3 046', 6);
INSERT INTO Wagon_Good (WagonId, GoodId) VALUES ('082 3 047', 6);
INSERT INTO Wagon_Good (WagonId, GoodId) VALUES ('082 3 048', 6);
INSERT INTO Wagon_Good (WagonId, GoodId) VALUES ('074 1 001', 4);
INSERT INTO Wagon_Good (WagonId, GoodId) VALUES ('074 1 002', 4);
INSERT INTO Wagon_Good (WagonId, GoodId) VALUES ('074 1 003', 4);
INSERT INTO Wagon_Good (WagonId, GoodId) VALUES ('074 1 004', 4);
INSERT INTO Wagon_Good (WagonId, GoodId) VALUES ('074 1 005', 4);
INSERT INTO Wagon_Good (WagonId, GoodId) VALUES ('074 1 006', 4);
INSERT INTO Wagon_Good (WagonId, GoodId) VALUES ('181 1 010', 4);
INSERT INTO Wagon_Good (WagonId, GoodId) VALUES ('181 1 011', 3);
INSERT INTO Wagon_Good (WagonId, GoodId) VALUES ('181 1 012', 4);
INSERT INTO Wagon_Good (WagonId, GoodId) VALUES ('181 1 013', 5);
INSERT INTO Wagon_Good (WagonId, GoodId) VALUES ('181 1 014', 5);
INSERT INTO Wagon_Good (WagonId, GoodId) VALUES ('333 0 001', 4);
INSERT INTO Wagon_Good (WagonId, GoodId) VALUES ('333 0 002', 3);
INSERT INTO Wagon_Good (WagonId, GoodId) VALUES ('333 0 003', 3);
INSERT INTO Wagon_Good (WagonId, GoodId) VALUES ('333 0 004', 3);
INSERT INTO Wagon_Good (WagonId, GoodId) VALUES ('333 0 005', 3);
INSERT INTO Wagon_Good (WagonId, GoodId) VALUES ('333 0 006', 3);
INSERT INTO Wagon_Good (WagonId, GoodId) VALUES ('333 0 007', 3);
INSERT INTO Wagon_Good (WagonId, GoodId) VALUES ('333 0 008', 3);
INSERT INTO Wagon_Good (WagonId, GoodId) VALUES ('333 0 009', 3);
INSERT INTO Wagon_Good (WagonId, GoodId) VALUES ('333 0 010', 3);