DECLARE
    P_FREIGHT_ID  FREIGHT.ID %TYPE          := 2040;
    P_TRAIN_ID    FREIGHT.TRAINID %TYPE     := 5421;
    P_ORIGIN      FREIGHT.ORIGIN %TYPE      := 50;
    P_DESTINATION FREIGHT.DESTINATION %TYPE := 13;
    P_WAGON_IDS   WAGON_ID_LIST             := wagon_id_list('356 3 077', '356 3 078');
BEGIN
    DELETE FROM FREIGHT WHERE ID = P_FREIGHT_ID AND TRAINID = P_TRAIN_ID AND ORIGIN = P_ORIGIN AND DESTINATION = P_DESTINATION;

    SYSTEM.PRC_REGISTER_FREIGHT(
            P_FREIGHT_ID => P_FREIGHT_ID,
            P_TRAIN_ID => P_TRAIN_ID,
            P_ORIGIN => P_ORIGIN,
            P_DESTINATION => P_DESTINATION,
            P_WAGON_IDS => P_WAGON_IDS
    );
    ROLLBACK;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);
END;